version: 1

host_url: https://paygod.godstabernacle.xyz:8080

stellar_network:
  network: TESTNET
  network_passphrase: Test SDF Network ; September 2015
  horizon_url: https://horizon-testnet.stellar.org

callback_api:
  base_url: https://paygod.godstabernacle.xyz:8081
  auth:
    type: JWT_TOKEN

platform_api:
  auth:
    type: JWT_TOKEN

languages: en

logging:
  level: WARN
  stellar_level: INFO

#data:
#  type: sqlite
#  url: jdbc:sqlite:anchor-platform.db
#  initial_connection_pool_size: 2
#  max_active_connections: 10
#  flyway_enabled: true
#  ddl_auto: update

data:
  type: postgres
  url: jdbc:postgresql://localhost:5432/anchorplatform
  username: anchoruser
  password: Edenlife247
  initial_connection_pool_size: 3
  max_active_connections: 10
  flyway_enabled: true
  ddl_auto: update

sep1:
  enabled: true
  toml:
    type: string
    value: |
      ACCOUNTS = []
      VERSION = "0.1.0"
      NETWORK_PASSPHRASE = "Test SDF Network ; September 2015"
      SIGNING_KEY = "GCJIKEKFS5YQP6OE7E6AALGD53NKFOHO6G7TGSMAB4X264SIFDOIVHP5"
      
      WEB_AUTH_ENDPOINT = "https://paygod.godstabernacle.xyz:8080/auth"
      KYC_SERVER = "https://paygod.godstabernacle.xyz:8080/sep12"
      TRANSFER_SERVER_SEP0024 = "https://paygod.godstabernacle.xyz:8080/sep24"
      DIRECT_PAYMENT_SERVER = "https://paygod.godstabernacle.xyz:8080/sep31"
      ANCHOR_QUOTE_SERVER = "https://paygod.godstabernacle.xyz:8080/sep38"
      
     [[CURRENCIES]]
     code = "NATUREUSD"
     issuer = "GA3BJUBNOIHANBJEKZFSQTCRB5CUQ4GSENQHVC5QNZGGSK3ILAZS6ATK"
     status = "test"
     name = "NATURE DOLLAR"
     is_asset_anchored = true
     anchor_asset_type = "crypto"
     anchor_asset = "NATUREUSD"
     redemption_instructions = "Get your asset via our wallets"
     
     [[CURRENCIES]]
     code = "NATURENGN"
     issuer = "GA3BJUBNOIHANBJEKZFSQTCRB5CUQ4GSENQHVC5QNZGGSK3ILAZS6ATK"
     status = "test"
     name = "NATURE NAIRA"
     is_asset_anchored = true
     anchor_asset_type = "crypto"
     anchor_asset = "NATURENGN"
     redemption_instructions = "Get your asset via our wallets" 
      
sep10:
  enabled: true
  home_domain: localhost:8080
  secret.sep10_signing_seed: GCJIKEKFS5YQP6OE7E6AALGD53NKFOHO6G7TGSMAB4X264SIFDOIVHP5
  secret.sep10_jwt_secret: secret
  

sep12:
  enabled: true

sep24:
  enabled: false
  interactive_url:
    base_url: https://paygod.godstabernacle.xyz:8091/sep24/interactive

sep31:
  enabled: true
  payment_type: STRICT_SEND
  deposit_info_generator_type: self

sep38:
  enabled: true

metrics:
  enabled: true
  extras_enabled: true
  run_interval: 30

events:
  enabled: true
  event_type_to_queue:
    quote_created: ap_event_quote_created
    transaction_created: ap_event_transaction_created
    transaction_status_changed: ap_event_transaction_status_changed
    transaction_error: ap_event_transaction_error
  publisher:
    type: kafka
    kafka:
      bootstrap_server: localhost:29092
      client_id:
      retries: 1
      linger_ms: 1000
      batch_size: 10

assets:
  type: json
  value: |
    {
      "assets": [
        {
          "schema": "stellar",
          "code": "NATUREUSD",
          "issuer": "GA3BJUBNOIHANBJEKZFSQTCRB5CUQ4GSENQHVC5QNZGGSK3ILAZS6ATK",
          "distribution_account": "GAIXTJGANTERAERDZN72GJTAU4YYEFH2HZNKDDBWQKFY7W6LC4WLLVHV",
          "significant_decimals": 4,
          "deposit": {
            "enabled": true,
            "fee_minimum": 0,
            "fee_percent": 1,
            "min_amount": 1,
            "max_amount": 1000000
          },
          "withdraw": {
            "enabled": true,
            "fee_fixed": 0,
            "fee_percent": 1,
            "min_amount": 1,
            "max_amount": 1000000
          },
          "send": {
            "fee_fixed": 0,
            "fee_percent": 1,
            "min_amount": 1,
            "max_amount": 1000000
          },
          "sep31": {
            "quotes_supported": true,
            "quotes_required": true,
            "sep12": {
              "sender": {
                "types": {
                  "sep31-sender": {
                    "description": "U.S. citizens limited to sending payments of less than $10,000 in value"
                  },
                  "sep31-large-sender": {
                    "description": "U.S. citizens that do not have sending limits"
                  },
                  "sep31-foreign-sender": {
                    "description": "non-U.S. citizens sending payments of less than $10,000 in value"
                  }
                }
              },
              "receiver": {
                "types": {
                  "sep31-receiver": {
                    "description": "U.S. citizens receiving USD"
                  },
                  "sep31-foreign-receiver": {
                    "description": "non-U.S. citizens receiving USD"
                  }
                }
              }
            },
            "fields": {
              "transaction": {
                "receiver_routing_number": {
                  "description": "routing number of the destination bank account"
                },
                "receiver_account_number": {
                  "description": "bank account number of the destination"
                },
                "type": {
                  "description": "type of deposit to make",
                  "choices": [
                    "SEPA",
                    "SWIFT"
                  ]
                }
              }
            }
          },
          "sep38": {
            "exchangeable_assets": [
              "iso4217:USD"
            ]
          },
          "sep24_enabled": true,
          "sep31_enabled": true,
          "sep38_enabled": true
        },
        {
          "schema": "stellar",
          "code": "NATURENGN",
          "issuer": "GA3BJUBNOIHANBJEKZFSQTCRB5CUQ4GSENQHVC5QNZGGSK3ILAZS6ATK",
          "distribution_account": "GAIXTJGANTERAERDZN72GJTAU4YYEFH2HZNKDDBWQKFY7W6LC4WLLVHV",
          "significant_decimals": 4,
          "deposit": {
            "enabled": true,
            "fee_minimum": 0,
            "fee_percent": 1,
            "min_amount": 1,
            "max_amount": 1000000
          },
          "withdraw": {
            "enabled": true,
            "fee_fixed": 0,
            "fee_percent": 1,
            "min_amount": 1,
            "max_amount": 1000000
          },
          "send": {
            "fee_fixed": 0,
            "fee_percent": 1,
            "min_amount": 1,
            "max_amount": 1000000
          },
          "sep31": {
            "quotes_supported": true,
            "quotes_required": true,
            "sep12": {
              "sender": {
                "types": {
                  "sep31-sender": {
                    "description": "Nigerian citizens limited to sending payments of less than $10,000 in value"
                  },
                  "sep31-large-sender": {
                    "description": "Nigerian citizens that do not have sending limits"
                  },
                  "sep31-foreign-sender": {
                    "description": "non-Nigerian citizens sending payments of less than $10,000 in value"
                  }
                }
              },
              "receiver": {
                "types": {
                  "sep31-receiver": {
                    "description": "Nigerian citizens receiving NGN"
                  },
                  "sep31-foreign-receiver": {
                    "description": "non-Nigerian citizens receiving NGN"
                  }
                }
              }
            },
            "fields": {
              "transaction": {
                "receiver_routing_number": {
                  "description": "routing number of the destination bank account"
                },
                "receiver_account_number": {
                  "description": "bank account number of the destination"
                },
                "type": {
                  "description": "type of deposit to make",
                  "choices": [
                    "SEPA",
                    "SWIFT"
                  ]
                }
              }
            }
          },
          "sep38": {
            "exchangeable_assets": [
              "iso4217:USD"
            ]
          },
          "sep24_enabled": true,
          "sep31_enabled": true,
          "sep38_enabled": true
        },
        {
          "schema": "iso4217",
          "code": "USD",
          "deposit": {
            "enabled": true,
            "fee_minimum": 0,
            "fee_percent": 1,
            "min_amount": 1,
            "max_amount": 10000
          },
          "withdraw": {
            "enabled": true,
            "fee_fixed": 0,
            "fee_percent": 1,
            "min_amount": 1,
            "max_amount": 10000
          },
          "send": {
            "fee_fixed": 0,
            "fee_percent": 1,
            "min_amount": 1,
            "max_amount": 10000
          },
          "sep38": {
            "exchangeable_assets": [
              "stellar:NATUREUSD:GA3BJUBNOIHANBJEKZFSQTCRB5CUQ4GSENQHVC5QNZGGSK3ILAZS6ATK",
              "stellar:NATURENGN:GA3BJUBNOIHANBJEKZFSQTCRB5CUQ4GSENQHVC5QNZGGSK3ILAZS6ATK"
            ],
            "country_codes": [
              "USA"
            ],
            "decimals": 4,
            "sell_delivery_methods": [
              {
                "name": "WIRE",
                "description": "Send USD directly to the Anchor's bank account."
              }
            ],
            "buy_delivery_methods": [
              {
                "name": "WIRE",
                "description": "Have USD sent directly to your bank account."
              }
            ]
          },
          "sep24_enabled": false,
          "sep31_enabled": false,
          "sep38_enabled": true
        }
      ]
    }

  
