version: 1

logging:
  level: INFO
  stellar_level: DEBUG

callback_api:
  base_url: http://localhost:8081
  auth:
    type: jwt

platform_api:
  auth:
    type: jwt

events:
  enabled: true
  publisher:
    kafka:
      bootstrap_server: kafka:29092

sep1:
  enabled: true
  toml:
    type: string
    value: |
      ACCOUNTS = ["GAIXTJGANTERAERDZN72GJTAU4YYEFH2HZNKDDBWQKFY7W6LC4WLLVHV"]
      VERSION = "2.5.0"
      NETWORK_PASSPHRASE = "Test SDF Network ; September 2015"
      SIGNING_KEY = "GCJIKEKFS5YQP6OE7E6AALGD53NKFOHO6G7TGSMAB4X264SIFDOIVHP5"
      TRANSFER_SERVER = "https://paygod.godstabernacle.xyz:8080/sep24"
      TRANSFER_SERVER_SEP0024 = "https://paygod.godstabernacle.xyz:8080/sep24"
      KYC_SERVER = "https://paygod.godstabernacle.xyz:8080/kyc"
      WEB_AUTH_ENDPOINT = "https://paygod.godstabernacle.xyz:8080/auth"
      DIRECT_PAYMENT_SERVER = "https://paygod.godstabernacle.xyz:8080/sep31"
      ANCHOR_QUOTE_SERVER = "https://paygod.godstabernacle.xyz:8080/sep38"

      [[CURRENCIES]]
      code = "NATUREUSD"
      issuer = "GA3BJUBNOIHANBJEKZFSQTCRB5CUQ4GSENQHVC5QNZGGSK3ILAZS6ATK"
      home-domain = "paygod.godstabernacle.xyz"
      status = "test"
      name = "NATURE DOLLAR"
      is_asset_anchored = true
      anchor_asset_type = "crypto"
      anchor_asset = "NATUREUSD"
      desc = "NATUREUSD is nature smartchain's test USD stable coin"
      redemption_instructions = "Get your asset via our wallets"

      [[CURRENCIES]]
      code = "NATURENGN"
      issuer = "GA3BJUBNOIHANBJEKZFSQTCRB5CUQ4GSENQHVC5QNZGGSK3ILAZS6ATK"
      home-domain = "paygod.godstabernacle.xyz"
      status = "test"
      name = "NATURE NAIRA"
      is_asset_anchored = true
      anchor_asset_type = "crypto"
      anchor_asset = "NATURENGN"
      desc = "NATURENGN is nature smartchain's test NGN stable coin"
      redemption_instructions = "Get your asset via our wallets"

      [DOCUMENTATION]
      ORG_NAME = "God's Tabernacle"
      ORG_URL = "https://www.godstabernacle.xyz"
      ORG_LOGO = "https://www.godstabernacle.xyz/logo"
      ORG_DESCRIPTION = "Recreo; Replete Terram"
      ORG_TWITTER = "nature2471"
      ORG_GITHUB = "nature-smartchain"
      ORG_OFFICIAL_EMAIL = "info@godstabernacle.xyz"
      ORG_SUPPORT_EMAIL = "support@godstabernacle.xyz"

      
sep10:
  enabled: true
  home_domain: paygod.godstabernacle.xyz:8080
  secret.sep10_signing_seed: SA2N44T5PKJ434T6WTAGJIGNER463IA7OUWPDQ5TBTWSKYJAK2UAGBCK
  secret.sep10_jwt_secret: jesuschistislordthereforbebornagain

sep12:
  enabled: true

sep24:
  enabled: false

sep31:
  enabled: true

sep38:
  enabled: true

assets:
  type: json
  value: |
    {
      "assets": [
          {
              "schema": "stellar",
              "code": "NATUREUSD",
              "issuer": "GA3BJUBNOIHANBJEKZFSQTCRB5CUQ4GSENQHVC5QNZGGSK3ILAZS6ATK",
             "distribution_account": "GAIXTJGANTERAERDZN72GJTAU4YYEFH2HZNKDDBWQKFY7W6LC4WLLVHV",
              "significant_decimals": 2,
              "deposit" : {
                  "enabled": true,
                  "fee_minimum": 0,
                  "fee_percent": 1,
                  "min_amount": 1,
                  "max_amount": 1000000
              },
              "withdraw": {
                  "enabled": true,
                  "fee_fixed": 0,
                  "fee_percent": 1,
                  "min_amount": 1,
                  "max_amount": 1000000
              },
              "send": {
                  "fee_fixed": 0,
                  "fee_percent": 1,
                  "min_amount": 1,
                  "max_amount": 1000000
              },
              "sep31" : {
                  "quotes_supported": true,
                  "quotes_required": true,
                  "sep12": {
                      "sender": {
                          "types": {
                              "sep31-sender": {
                                  "description": "U.S. citizens limited to sending payments of less than $10,000 in value"
                              },
                              "sep31-large-sender": {
                                  "description": "U.S. citizens that do not have sending limits"
                              },
                              "sep31-foreign-sender": {
                                  "description": "non-U.S. citizens sending payments of less than $10,000 in value"
                              }
                          }
                      },
                      "receiver": {
                          "types": {
                              "sep31-receiver": {
                                  "description": "U.S. citizens receiving USD"
                              },
                              "sep31-foreign-receiver": {
                                  "description": "non-U.S. citizens receiving USD"
                              }
                          }
                      }
                  },
                  "fields": {
                      "transaction": {
                          "receiver_routing_number": {
                              "description": "routing number of the destination bank account"
                          },
                          "receiver_account_number": {
                              "description": "bank account number of the destination"
                          },
                          "type": {
                              "description": "type of deposit to make",
                              "choices": [
                                  "SEPA",
                                  "SWIFT"
                              ]
                          }
                      }
                  }
              },
              "sep38": {
                  "exchangeable_assets": [
                      "iso4217:USD"
                  ]
              },
              "sep24_enabled": true,
              "sep31_enabled": true,
              "sep38_enabled": true
          },
          {
              "schema": "stellar",
              "code": "NATURENGN",
              "issuer": "GA3BJUBNOIHANBJEKZFSQTCRB5CUQ4GSENQHVC5QNZGGSK3ILAZS6ATK",
              "distribution_account": "GAIXTJGANTERAERDZN72GJTAU4YYEFH2HZNKDDBWQKFY7W6LC4WLLVHV",
              "significant_decimals": 4,
              "deposit" : {
                  "enabled": true,
                  "fee_minimum": 0,
                  "fee_percent": 1,
                  "min_amount": 1,
                  "max_amount": 1000000
              },
              "withdraw": {
                  "enabled": true,
                  "fee_fixed": 0,
                  "fee_percent": 1,
                  "min_amount": 1,
                  "max_amount": 1000000
              },
              "send": {
                  "fee_fixed": 0,
                  "fee_percent": 1,
                  "min_amount": 1,
                  "max_amount": 1000000
              },
              "sep31" : {
                  "quotes_supported": true,
                  "quotes_required": true,
                  "sep12": {
                      "sender": {
                          "types": {
                              "sep31-sender": {
                                  "description": "Nigerian citizens limited to sending payments of less than $10,000 in value"
                              },
                              "sep31-large-sender": {
                                  "description": "Nigerian citizens that do not have sending limits"
                              },
                              "sep31-foreign-sender": {
                                  "description": "non-Nigerian. citizens sending payments of less than $10,000 in value"
                              }
                          }
                      },
                      "receiver": {
                          "types": {
                              "sep31-receiver": {
                                  "description": "Nigerian citizens receiving NGN"
                              },
                              "sep31-foreign-receiver": {
                                  "description": "non-Nigerian citizens receiving NGN"
                              }
                          }
                      }
                  },
                  "fields": {
                      "transaction": {
                          "receiver_routing_number": {
                              "description": "routing number of the destination bank account"
                          },
                          "receiver_account_number": {
                              "description": "bank account number of the destination"
                          },
                          "type": {
                              "description": "type of deposit to make",
                              "choices": [
                                  "SEPA",
                                  "SWIFT"
                              ]
                          }
                      }
                  }
              },
              "sep38": {
                  "exchangeable_assets": [
                      "iso4217:USD"
                  ]
              },
              "sep24_enabled": true,
              "sep31_enabled": true,
              "sep38_enabled": true
          },
          {
              "schema": "iso4217",
              "code": "USD",
              "deposit" : {
                  "enabled": true,
                  "fee_minimum": 0,
                  "fee_percent": 1,
                  "min_amount": 1,
                  "max_amount": 10000
              },
              "withdraw": {
                  "enabled": true,
                  "fee_fixed": 0,
                  "fee_percent": 1,
                  "min_amount": 1,
                  "max_amount": 10000
              },
              "send": {
                  "fee_fixed": 0,
                  "fee_percent": 1,
                  "min_amount": 1,
                  "max_amount": 10000
              },
              "sep38": {
                  "exchangeable_assets": [
                      "stellar:NATUREUSD:GA3BJUBNOIHANBJEKZFSQTCRB5CUQ4GSENQHVC5QNZGGSK3ILAZS6ATK",
                      "stellar:NATURENGN:GA3BJUBNOIHANBJEKZFSQTCRB5CUQ4GSENQHVC5QNZGGSK3ILAZS6ATK"
                  ],
                  "country_codes": ["USA"],
                  "decimals": 4,
                  "sell_delivery_methods": [
                      {
                          "name": "WIRE",
                          "description": "Send USD directly to the Anchor's bank account."
                      }
                  ],
                  "buy_delivery_methods": [
                      {
                          "name": "WIRE",
                          "description": "Have USD sent directly to your bank account."
                      }
                  ]
              },
              "sep24_enabled": false,
              "sep31_enabled": false,
              "sep38_enabled": true
          }
      ]
    }

################################
## Data Configuration
################################
data:

  ## DB credentials are specified in @environment_variables SECRET_DATA_USERNAME, SECRET_DATA_PASSWORD

  ## @param: type
  ## @supported_values:
  ##    `h2` (in-memory), `sqlite` (local), `postgres` (local), `aurora` (postgres on AWS)
  ## Type of storage.
  ## If this is set to `aurora`,
  ##    @required_secrets: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION
  #
  type: postgres

  server: db:5432

  database: postgres

  ## @param: initial_connection_pool_size
  ## @type: integer
  ## Initial number of connections
  ## For `sqlite`, set this to 1 to avoid database file lock exception
  #
  initial_connection_pool_size: 1

  ## @param: max_active_connections
  ## @type: integer
  ## Maximum number of db active connections
  ## For `sqlite`, set this to 1 to avoid database file lock exception
  #
  max_active_connections: 10

  ## @param: flyway_enabled
  ## @type: bool
  ## Whether to enable flyway.
  ## Should be disabled for `sqlite` because certain features that flyway uses
  ## (ex: addForeignKeyConstraint) are not supported.
  #
  flyway_enabled: true

  ## @param: flyway_enabled
  ## @type: string
  ## Location on disk where migrations are stored if flyway is enabled.
  #
  flyway_location: /db/migration

  ## @param: hikari_max_lifetime
  ## @type: integer
  ## Maximum connection time before expiration
  ## Only valid when database `type` is `aurora`.
  ## Recommended setting is 14 minutes because IAM tokens are valid for 15 min.
  #
  # hikari_max_lifetime: 840000
