version: 1

sep1:
  toml:
    type: string
    value: |
      ACCOUNTS = []
      VERSION = "0.1.0"
      NETWORK_PASSPHRASE = "Test SDF Network ; September 2015"
      SIGNING_KEY = "GCHLHDBOKG2JWMJQBTLSL5XG6NO7ESXI2TAQKZXCXWXB5WI2X6W233PR"     
      WEB_AUTH_ENDPOINT = "https://paygod.godstabernacle.xyz:8080/auth"
      TRANSFER_SERVER_SEP0024 = "https://paygod.godstabernacle.xyz:8080/sep24"
      
      [[CURRENCIES]]
      code = "NATUREUSD"
      issuer = "GA3BJUBNOIHANBJEKZFSQTCRB5CUQ4GSENQHVC5QNZGGSK3ILAZS6ATK"
      status = "test"
      is_asset_anchored = true
      anchor_asset_type = "fiat"
      desc = "A test NATUREUSD issued by Stellar."

assets:
  type: json
  value: |
    {
      "assets": [
        {
          "schema": "stellar",
          "code": "NATUREUSD",
          "issuer": "GA3BJUBNOIHANBJEKZFSQTCRB5CUQ4GSENQHVC5QNZGGSK3ILAZS6ATK",
          "distribution_account": "GAIXTJGANTERAERDZN72GJTAU4YYEFH2HZNKDDBWQKFY7W6LC4WLLVHV",
          "significant_decimals": 2,
          "deposit": {
            "enabled": true,
            "min_amount": 1,
            "max_amount": 1000000
          },
          "withdraw": {
            "enabled": true,
            "min_amount": 1,
            "max_amount": 1000000
          },
          "sep24_enabled": true
        }
      ]
    }

