version: 1

sep1:
  toml:
    type: string
    value: |
      ACCOUNTS = ["GAIXTJGANTERAERDZN72GJTAU4YYEFH2HZNKDDBWQKFY7W6LC4WLLVHV"]
      VERSION = "2.5.0"
      NETWORK_PASSPHRASE = "Test SDF Network ; September 2015"
      SIGNING_KEY = "GCJIKEKFS5YQP6OE7E6AALGD53NKFOHO6G7TGSMAB4X264SIFDOIVHP5"
      KYC_SERVER = "https://paygod.godstabernacle.xyz:8080/kyc"
      WEB_AUTH_ENDPOINT = "https://paygod.godstabernacle.xyz:8080/auth"
      DIRECT_PAYMENT_SERVER = "https://paygod.godstabernacle.xyz:8080/sep31"
      ANCHOR_QUOTE_SERVER = "https://paygod.godstabernacle.xyz:8080/sep38"

      
     [[CURRENCIES]]
     code = "NATUREUSD"
     issuer = "GA3BJUBNOIHANBJEKZFSQTCRB5CUQ4GSENQHVC5QNZGGSK3ILAZS6ATK"
     status = "test"
     name = "NATURE DOLLAR"
     is_asset_anchored = true
     anchor_asset_type = "crypto"
     anchor_asset = "NATUREUSD"
     redemption_instructions = "Get your asset via our wallets"
     
     [[CURRENCIES]]
     code = "NATURENGN"
     issuer = "GA3BJUBNOIHANBJEKZFSQTCRB5CUQ4GSENQHVC5QNZGGSK3ILAZS6ATK"
     status = "test"
     name = "NATURE NAIRA"
     is_asset_anchored = true
     anchor_asset_type = "crypto"
     anchor_asset = "NATURENGN"
     redemption_instructions = "Get your asset via our wallets"

     [DOCUMENTATION]
     ORG_NAME = "God's Tabernacle"
     ORG_URL = "https://www.godstabernacle.xyz"
     ORG_LOGO = "https://www.godstabernacle.xyz/logo"
     ORG_DESCRIPTION = "Recreo; Replete Terram"
     ORG_TWITTER = "nature2471"
     ORG_GITHUB = "nature-smartchain"
     ORG_OFFICIAL_EMAIL = "info@godstabernacle.xyz"
     ORG_SUPPORT_EMAIL = "support@godstabernacle.xyz"


assets:
  type: json
  value: |
      {
        "assets": [
          {
            "schema": "stellar",
            "code": "NATUREUSD",
            "issuer": "GA3BJUBNOIHANBJEKZFSQTCRB5CUQ4GSENQHVC5QNZGGSK3ILAZS6ATK",
            "distribution_account": "GAIXTJGANTERAERDZN72GJTAU4YYEFH2HZNKDDBWQKFY7W6LC4WLLVHV",
            "significant_decimals": 4,
            "send": {
              "fee_fixed": 0,
              "fee_percent": 1,
              "min_amount": 1,
              "max_amount": 1000000
            },
            "sep31" : {
              "quotes_supported": true,
              "quotes_required": true,
              "sep12": {
                "sender": {
                  "types": {
                    "sep31-sender": {
                      "description": "U.S. citizens limited to sending payments of less than $10,000 in value"
                    },
                    "sep31-large-sender": {
                      "description": "U.S. citizens that do not have sending limits"
                    },
                    "sep31-foreign-sender": {
                      "description": "non-U.S. citizens sending payments of less than $10,000 in value"
                    }
                  }
                },
                "receiver": {
                  "types": {
                    "sep31-receiver": {
                      "description": "U.S. citizens receiving USD"
                    },
                    "sep31-foreign-receiver": {
                      "description": "non-U.S. citizens receiving USD"
                    }
                  }
                }
              },
              "fields": {
                "transaction": {
                  "receiver_routing_number": {
                    "description": "routing number of the destination bank account"
                  },
                  "receiver_account_number": {
                    "description": "bank account number of the destination"
                  },
                  "type": {
                    "description": "type of deposit to make",
                    "choices": [
                      "SEPA",
                      "SWIFT"
                    ]
                  }
                }
              }
            },
            "sep38": {
              "exchangeable_assets": [
                "iso4217:USD"
              ]
            },
            "sep31_enabled": true,
            "sep38_enabled": true
          }
        ]
      }

